# Generated by Django 4.0.5 on 2022-06-24 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('debts', models.ManyToManyField(blank=True, to='ledger.debt')),
                ('members', models.ManyToManyField(to='ledger.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_share', models.IntegerField(default=0)),
                ('owed_share', models.IntegerField(default=0)),
                ('net_balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_group', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.group')),
                ('paid_owed', models.ManyToManyField(to='ledger.expenseuser')),
                ('repayments', models.ManyToManyField(to='ledger.debt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='ledger.userprofile'),
        ),
        migrations.AddField(
            model_name='debt',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='ledger.userprofile'),
        ),
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('split_choices', models.CharField(choices=[('E', 'Equally'), ('U', 'Unequally'), ('P', 'Percentage')], default='E', max_length=30)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='ledger.userprofile')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.group')),
                ('to_members', models.ManyToManyField(to='ledger.userprofile')),
            ],
        ),
    ]
