# Generated by Django 4.0.5 on 2022-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='split_choices',
            field=models.CharField(choices=[('BY_EQUALLY', 'Equally'), ('BY_UNEQUALLY', 'Unequally'), ('BY_PERCENTAGE', 'Percentage')], default='BY_EQUALLY', max_length=30),
        ),
    ]
