# Generated by Django 4.0.5 on 2022-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_addexpense_split_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='split_choices',
            field=models.CharField(choices=[('E', 'Equally'), ('U', 'Unequally'), ('P', 'Percentage')], default='E', max_length=30),
        ),
    ]
