# Generated by Django 4.0.5 on 2022-07-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_addexpense_split_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ledger.expense')),
            ],
        ),
    ]
