# Generated by Django 4.0.6 on 2022-07-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_expensereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group'},
        ),
    ]
