# Generated by Django 4.0.6 on 2022-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
