# Generated by Django 4.0.6 on 2022-07-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_group_options_alter_group_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'group'},
        ),
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
    ]
