# Generated by Django 4.0.6 on 2022-07-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_group_options_alter_group_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(blank=True, related_name='debts', to='ledger.debt'),
        ),
    ]
