# Generated by Django 4.0.6 on 2022-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_group_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(blank=True, related_name='debts_id', to='ledger.debt'),
        ),
    ]
